import { firebaseDb } from '../firebase'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'
export const ADD_TODO_ERROR = 'ADD_TODO_ERROR'
export const TOGGLE_TODO_REQUEST = 'TOGGLE_TODO_REQUEST'
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS'
export const TOGGLE_TODO_ERROR = 'TOGGLE_TODO_ERROR'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'